# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"%\n\x0eProductRequest\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\x05\"&\n\x0fProductResponse\x12\x13\n\x0btotal_price\x18\x01 \x01(\x02\x32J\n\x0eProductService\x12\x38\n\x13\x43\x61lculateTotalPrice\x12\x0f.ProductRequest\x1a\x10.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTREQUEST']._serialized_start=17
  _globals['_PRODUCTREQUEST']._serialized_end=54
  _globals['_PRODUCTRESPONSE']._serialized_start=56
  _globals['_PRODUCTRESPONSE']._serialized_end=94
  _globals['_PRODUCTSERVICE']._serialized_start=96
  _globals['_PRODUCTSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
